//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRepairService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP4Entities : DbContext
    {
        public UP4Entities()
            : base("name=UP4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeTransfer> EmployeeTransfer { get; set; }
        public virtual DbSet<EquipmentUnit> EquipmentUnit { get; set; }
        public virtual DbSet<EquipmentUnitTransfer> EquipmentUnitTransfer { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<SparePart> SparePart { get; set; }
        public virtual DbSet<SparePartRequest> SparePartRequest { get; set; }
    }
}
