//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRepairService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartRequest
    {
        public int Id { get; set; }
        public Nullable<int> RepairId { get; set; }
        public Nullable<int> SparePartId { get; set; }
        public int Count { get; set; }
    
        public virtual Repair Repair { get; set; }
        public virtual SparePart SparePart { get; set; }
    }
}
