//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRepairService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SparePart()
        {
            this.SparePartRequest = new HashSet<SparePartRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Name { get; set; }
        public int StockCount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartRequest> SparePartRequest { get; set; }
    }
}
